### ISSUE TITLE
救救flutter小白

### ISSUE THREAD

**Issue by lxfeng1997** [sm9i/aliyun_video#2]
大佬，我们想要接入阿里云短视频的sdk。遇到很多问题，您方便留个联系方式，可以有偿问答。救救flutter小白

**Comment by sm9i** [comment]
我曹。。。这个只是之前简单用的。后期就没搞。。建议你自己搞一个。。我页面都是 copy官网的demo的 建议自己实现。。

**Comment by sm9i** [comment]
我可以帮你，，但技术外包就算了。。

**Comment by lxfeng1997** [comment]
大佬，那我们先加个联系方式?

**Comment by sm9i** [comment]
46488407 qq
